# Generated by Django 2.2 on 2020-11-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsercart',
            name='total_product',
            field=models.IntegerField(default=1, verbose_name='Total product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_product',
            field=models.IntegerField(default=1, verbose_name='Total product'),
        ),
    ]
