# Generated by Django 2.2 on 2020-11-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201101_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsercart',
            name='total_product',
            field=models.IntegerField(default=0, verbose_name='Total product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_product',
            field=models.IntegerField(default=0, verbose_name='Total product'),
        ),
    ]
